Importing the Dependencies

In [4]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

Data Pre-Processing

In [7]:
#  Loading the dataset
mail_data = pd.read_csv('/content/mail data.csv')
mail_data

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
# Information about the dataset
mail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [10]:
# Dimension of the dataset
mail_data.shape

(5572, 2)

In [12]:
mail_data.describe()

       Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [13]:
# Replacing yhe null values with a null String
data = mail_data.where((pd.notnull(mail_data)),'')

In [14]:
# printing the first 5 rows  of the df
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
# Label spam mail as 0 and ham  mail as 1
data.loc[data['Category'] == 'spam','category',] = 0
data.loc[data['Category'] == 'ham','category',] = 1

In [21]:
# Separating the data as texts and label
X = data['Message']
Y = data['category']

In [23]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [24]:
print(Y)

0       1.0
1       1.0
2       0.0
3       1.0
4       1.0
       ...
5567    0.0
5568    1.0
5569    1.0
5570    1.0
5571    1.0
Name: category, Length: 5572, dtype: float64

Splitting the data into training data & test data

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2)

In [26]:
print(X.shape, X_train.shape, X_test.shape)

(5572,) (4457,) (1115,)

Feature Extraction

In [54]:
# Transform the test data to feature vectors that can used as input to the Logistic regreesion
feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase =True)
X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

# convert Y_train and Y_test values as intergers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [36]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34768 stored elements and shape (4457, 7458)>
  Coords	Values
  (0, 6927)	0.48935591439341625
  (0, 6586)	0.44333254982109394
  (0, 3958)	0.6161071828926097
  (0, 4334)	0.42941702167641554
  (1, 3168)	0.5869421390016224
  (1, 6971)	0.4281243465155688
  (1, 1428)	0.5869421390016224
  (1, 2121)	0.35736171430221464
  (2, 6878)	0.35749230587184955
  (2, 1876)	0.28751725124107325
  (2, 5894)	0.35749230587184955
  (2, 806)	0.26730249393705324
  (2, 5695)	0.35749230587184955
  (2, 4884)	0.35749230587184955
  (2, 3852)	0.3408491178137899
  (2, 7353)	0.31988118061968496
  (2, 5115)	0.3408491178137899
  (3, 1876)	0.3080768784015236
  (3, 7297)	0.22192369472149484
  (3, 7000)	0.30072945056088285
  (3, 7065)	0.32795623716393424
  (3, 2060)	0.24915048132454623
  (3, 5005)	0.3169028431039865
  (3, 7248)	0.23571908490908416
  (3, 300)	0.2915969875465198
  :	:
  (4454, 4627)	0.3831814754124698
  (4454, 311)	0.19547195974237946
  (4454, 5068)	0.22284357632450164
  (4454, 1094)	0.24862733340971144
  (4454, 1575)	0.20946314330145205
  (4454, 666)	0.28653660324238944
  (4454, 2244)	0.2526916142542512
  (4454, 7084)	0.2689097965804433
  (4454, 571)	0.3005277868014621
  (4454, 5077)	0.3005277868014621
  (4454, 297)	0.3005277868014621
  (4455, 3084)	0.3019392955127119
  (4455, 4614)	0.4677148905542796
  (4455, 3701)	0.546620099025937
  (4455, 7075)	0.6255253074975946
  (4456, 6575)	0.15362974460832007
  (4456, 5820)	0.18767970267638426
  (4456, 7376)	0.20404881687716278
  (4456, 7033)	0.43304344994724825
  (4456, 380)	0.24893867331233713
  (4456, 2509)	0.20620887737471993
  (4456, 7032)	0.2868954144677231
  (4456, 909)	0.26924653489772427
  (4456, 5009)	0.6018082365591317
  (4456, 3768)	0.30090411827956587

Training the Model

In [38]:
# Training the Logistic Regression model with the training dataset
model = LogisticRegression()

In [40]:
model.fit(X_train_features, Y_train)

LogisticRegression()

Model Evaluation

In [52]:
#Accuracy score for training data
X_train_prediction = model.predict(X_train_features)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print("Accuracy score of training data: ",training_data_accuracy)

Accuracy score of training data:  0.9685887368184878

In [45]:
#Accuracy score for testing data
X_test_prediction = model.predict(X_test_features)
testing_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print("Accuracy score of testing data",testing_data_accuracy)

Accuracy score of testing data 0.9533632286995516

Buliding a Predictive System

In [56]:
#Making the Predictive system
input_mail = ["WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only."]

#Converting text into feature vectors
input_data_features = feature_extraction.transform(input_mail)

#Making prediction
prediction = model.predict(input_data_features)
print(prediction)

if (prediction[0]==1):
  print('Ham mail')
else:
  print('Spam mail')

[0]
Spam mail